name: olmo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.5.1
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - numpy<2.0
  - pip
  - pip:
    - datasets
    - transformers
    - wandb
    - tqdm
    - cached-path>=1.6.6
    - requests
    - packaging
    - rich
    - omegaconf
    - safetensors
    - importlib_resources
    - ai2-olmo-eval==0.5.0 